config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, accept: %i(new create edit update)
    resources :microposts, :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= raw t("layouts.footer.left_text") %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"), about_path %></li>
      <li><%= link_to t("static_pages.contact.title"), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%= t(".news") %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("app_name"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= active_nav root_path %>">
          <%= link_to t("static_pages.home.title"), root_path %>
        </li>
        <li class="<%= active_nav help_path %>">
          <%= link_to t("static_pages.help.title"), help_path %>
        </li>
        <% if logged_in? %>
          <li class="<%= active_nav users_path %>">
            <%= link_to t("layouts.header.users"), users_path %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t("layouts.header.account") %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="<%= active_nav current_user %>">
                <%= link_to t("layouts.header.profile"),
                  current_user %></li>
              <li class="<%= active_nav edit_user_path(current_user) %>">
                <%= link_to t("layouts.header.settings"),
                  edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t("layouts.header.logout"),
                logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="<%= active_nav login_path %>">
            <%= link_to t("layouts.header.login"), login_path %>
          </li>
        <% end %>
        <li class="locale">
          <%= link_to :en, root_path(locale: :en),
            class: (:active if params[:locale] == "en") %>
          <%= link_to :vi, root_path(locale: :vi),
            class: (:active if params[:locale] == "vi") %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application",
  "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body data-locale="<%= I18n.locale %>">
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>